In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",
    header=None,
)

df.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [4]:
X = df.values[:, :4].astype(float) # all rows (:), columns 0 -> 3 (:4)
y = df.values[:, 4] # all rows (:), 4th column (4)
X.shape, y.shape

((150, 4), (150,))

In [6]:
import numpy as np

a = np.array([0, 1, 2, 3, 4])
mask = np.array([True, True, True, False, False])
print("mask", mask)
print("~mask", ~mask)
print("a[mask]", a[mask])
print("a[~mask]", a[~mask])

mask [ True  True  True False False]
~mask [False False False  True  True]
a[mask] [0 1 2]
a[~mask] [3 4]


In [7]:
mask = np.array([True] * 120 + [False] * 30)
mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False,

In [8]:
np.random.shuffle(mask)
mask

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True,  True,  True, False,  True,  True, False,
       False,  True,  True, False,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,

In [9]:
X_train = X[mask]
X_test = X[~mask]
y_train = y[mask]
y_test = y[~mask]
(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

((120, 4), (30, 4), (120,), (30,))

In [10]:
from collections import Counter
Counter(y_train), Counter(y_test)


(Counter({'Iris-setosa': 42, 'Iris-versicolor': 36, 'Iris-virginica': 42}),
 Counter({'Iris-setosa': 8, 'Iris-versicolor': 14, 'Iris-virginica': 8}))

In [11]:
class KNearestNeighbors:
    def __init__(self, k, distance_metric="euclidean"):
        self.k = k
        self.distance_metric = distance_metric

    def fit(self, X, y):
        pass

    def predict(self, X):
        pass

In [12]:
class KNearestNeighbors:
    def __init__(self, k, distance_metric="euclidean"):
        self.k = k
        self.distance_metric = distance_metric

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        pass

In [13]:
def naive_distance(X_train, X_test, distance):
    distance_matrix = np.zeros((X_train.shape[0], X_test.shape[0]))
    for i in range(X_train.shape[0]):
        for j in range(X_test.shape[0]):
            distance_matrix[i,j] = distance(X_train[i], X_test[j])
    return distance_matrix

In [14]:
def euclidean_non_numpy(p, q):
    cumul = 0
    for i in range(len(p)):
        cumul += (p[i] - q[i])**2
    return cumul ** 0.5
    
def euclidean_numpy(p, q):
    return ((p-q)**2).sum()**.5

In [15]:
from timeit import timeit

# p and q are 200-dimensional random vectors
p = np.random.random(200)
q = np.random.random(200)

time_nnp = timeit(lambda: euclidean_non_numpy(p,q), number=10000)
time_np = timeit(lambda: euclidean_numpy(p,q), number=10000)

print("euclidean_non_numpy", time_nnp)
print("euclidean_numpy", time_np)
print("Ratio", time_nnp/time_np)

euclidean_non_numpy 4.469971100000009
euclidean_numpy 0.15882460000000265
Ratio 28.144072769583143


In [16]:
X_train_reshaped = np.expand_dims(X_train, 1)
X_train_reshaped.shape

(120, 1, 4)

In [18]:
X_diff = X_train_reshaped - X_test
X_diff.shape

(120, 30, 4)

In [19]:
dist_matrix = ((X_diff**2).sum(axis=2))**.5
dist_matrix.shape

(120, 30)

In [20]:
i = 25
j = 14
dist_matrix[i,j], euclidean_numpy(X_train[i], X_test[j])

(2.3043437243605824, 2.3043437243605824)

In [21]:
def euclidean(X_train, X_test):
    X_train_reshaped = np.expand_dims(X_train, 1)
    X_diff = X_train_reshaped - X_test
    dist_matrix = ((X_diff**2).sum(axis=2))**.5
    return dist_matrix

X_tr = np.random.random((120, 4))
X_te = np.random.random((30, 4))

time_naive = timeit(lambda: naive_distance(X_tr, X_te, euclidean_numpy), number=100)
time_numpy = timeit(lambda: euclidean(X_tr, X_te), number=100)

print("Naive", time_naive)
print("Numpy", time_numpy)
print("Ratio", time_naive / time_numpy)

Naive 4.760240999999951
Numpy 0.03253129999995963
Ratio 146.32802869869505


In [22]:
dot_prods = X_train @ X_test.T # the @ operator is a short-hand for the matrix multiplication function
dot_prods.shape

(120, 30)

In [23]:
X_train_norm = ((X_train**2).sum(axis=1)**.5).reshape(-1,1)
X_test_norm = ((X_test**2).sum(axis=1)**.5).T

In [24]:
dist_matrix = 1 - abs(dot_prods / X_train_norm.reshape(-1,1) / X_test_norm)

In [25]:
def cosine(X_train, X_test):
    X_train_norm = ((X_train**2).sum(axis=1)**.5).reshape(-1,1)
    X_test_norm = ((X_test**2).sum(axis=1)**.5)
    dot_prods = X_train @ X_test.T
    dist_matrix = 1 - abs(dot_prods / X_train_norm.reshape(-1,1) / X_test_norm)
    return dist_matrix

In [26]:
def manhattan(X_train, X_test):
    X_train_reshaped = np.expand_dims(X_train, 1)
    X_diff = X_train_reshaped - X_test
    dist_matrix = abs(X_diff).sum(axis=2)
    return dist_matrix

In [27]:
manhattan(X_train, X_test)

array([[ 0.7,  1.2,  0.6, ...,  9.9,  7.3,  7.7],
       [ 0.5,  2. ,  0.6, ..., 10.7,  7.5,  8.3],
       [ 0.5,  2. ,  0.6, ..., 10.7,  7.3,  8.3],
       ...,
       [ 7.2,  7.1,  7.5, ...,  3.4,  1.8,  1.4],
       [ 7.8,  6.9,  7.3, ...,  3.4,  2. ,  0.4],
       [ 6.3,  6.2,  6.6, ...,  4.3,  1.5,  1.9]])

In [28]:
class KNearestNeighbors:
    def __init__(self, k, distance_metric="euclidean"):
        self.k = k
        self.distance_metric = distance_metric

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train
        
        self.X_train_reshaped = np.expand_dims(self.X_train, 1)
        self.X_train_norm = ((self.X_train**2).sum(axis=1)**.5).reshape(-1,1)

    def _euclidean(self, X_test):
        X_diff = self.X_train_reshaped - X_test
        dist_matrix = ((X_diff**2).sum(axis=2))**.5
        return dist_matrix
    
    def _cosine(self, X_test):
        X_test_norm = ((X_test**2).sum(axis=1)**.5)
        dot_prods = X_train @ X_test.T
        dist_matrix = 1 - abs(dot_prods / self.X_train_norm.reshape(-1,1) / X_test_norm)
        return dist_matrix
    
    def _manhattan(self, X_test):
        X_diff = self.X_train_reshaped - X_test
        dist_matrix = abs(X_diff).sum(axis=2)
        return dist_matrix

    def predict(self, X_test):
        pass

In [29]:
a = np.array([52, 12, 99, 4])
ndx = np.argsort(a)
print("ndx", ndx)
print("a[ndx]", a[ndx])

ndx [3 1 0 2]
a[ndx] [ 4 12 52 99]


In [30]:
k = 3
knn = dist_matrix.argsort(axis=0)[:k, :].T
knn

array([[  9,  38,  28],
       [  4,  17,  16],
       [ 24,   2,   5],
       [ 30,  28,   7],
       [ 28,  30,   7],
       [ 38,  15,  23],
       [ 29,  23,  41],
       [  5,  31,  40],
       [ 56,  72,  44],
       [ 48,  64,  75],
       [ 43,  48,  77],
       [ 58,  61,  42],
       [ 67,  57,  48],
       [105, 103,  45],
       [ 58,  42,  60],
       [ 56,  72,  65],
       [ 42,  60,  61],
       [ 44,  72,  77],
       [ 44,  63,  46],
       [ 47,  52,  59],
       [ 42,  60,  58],
       [ 72,  42,  60],
       [112,  81, 113],
       [ 96,  81, 112],
       [ 66, 107, 100],
       [108,  86, 117],
       [105, 100, 103],
       [ 47, 105,  52],
       [ 83,  82,  80],
       [118,  96, 114]], dtype=int64)

In [31]:
y_train[knn]

array([['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor'],
       ['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor'],
       ['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor'],
       ['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor'],
       ['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor'],
       ['Iris-virginica', 'Iris-virginica', 'Iris-versicolor'],
       ['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor'],
       ['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor'],
       ['Iris-versicolor', 'Iris-versicolo

In [32]:
list(map(Counter, y_train[knn]))

[Counter({'Iris-setosa': 3}),
 Counter({'Iris-setosa': 3}),
 Counter({'Iris-setosa': 3}),
 Counter({'Iris-setosa': 3}),
 Counter({'Iris-setosa': 3}),
 Counter({'Iris-setosa': 3}),
 Counter({'Iris-setosa': 3}),
 Counter({'Iris-setosa': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-virginica': 2, 'Iris-versicolor': 1}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-versicolor': 3}),
 Counter({'Iris-virginica': 3}),
 Counter({'Iris-virginica': 3}),
 Counter({'Iris-versicolor': 1, 'Iris-virginica': 2}),
 Counter({'Iris-virginica': 3}),
 Counter({'Iris-virginica': 3}),
 Counter({'Iris-versicolor': 2, 'Iris-virginica': 1}),
 Counter({'Iris-virgi

In [33]:
def majority_voting(votes):
    count = Counter(votes)
    return count.most_common(1)[0][0] # most_common(n) returns a list with the n most recurring votes (n=1 -> top vote)

np.array(list(map(majority_voting, y_train[knn])))
np.array([ majority_voting(y_train[knn][i]) for i in range(len(y_train[knn])) ])

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [34]:
def _majority_voting(votes):
    count = Counter(votes)
    return count.most_common(1)[0][0] # most_common(n) returns a list with the n most recurring votes (n=1 -> top vote)

class KNearestNeighbors:
    def __init__(self, k, distance_metric="euclidean"):
        self.k = k
        self.distance_metric = distance_metric

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train
        
        self.X_train_reshaped = np.expand_dims(self.X_train, 1)
        self.X_train_norm = ((self.X_train**2).sum(axis=1)**.5).reshape(-1,1)
        
    def _euclidean(self, X_test):
        X_diff = self.X_train_reshaped - X_test
        dist_matrix = ((X_diff**2).sum(axis=2))**.5
        
        return dist_matrix
    
    def _cosine(self, X_test):
        X_test_norm = ((X_test**2).sum(axis=1)**.5).T
        dot_prods = X_train @ X_test.T
        dist_matrix = 1 - abs(dot_prods / self.X_train_norm.reshape(-1,1) / X_test_norm)
        
        return dist_matrix
    
    def _manhattan(self, X_test):
        X_diff = self.X_train_reshaped - X_test
        dist_matrix = abs(X_diff).sum(axis=2)
        return dist_matrix

    def predict(self, X_test):
        if self.distance_metric == "euclidean":
            dist_matrix = self._euclidean(X_test)
        elif self.distance_metric == "cosine":
            dist_matrix = self._cosine(X_test)
        elif self.distance_metric == "manhattan":
            dist_matrix = self._manhattan(X_test)
        else:
            raise Exception("Unknown distance metric")
        knn = dist_matrix.argsort(axis=0)[:self.k, :].T
        y_pred = np.array([ majority_voting(self.y_train[knn][i]) for i in range(len(self.y_train[knn])) ])
        
        return y_pred

In [35]:
knn_model = KNearestNeighbors(3, "cosine")
knn_model.fit(X_train, y_train)
y_pred = knn_model.predict(X_test)
y_pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [36]:
def accuracy_score(y_true, y_pred):
    return (y_true==y_pred).sum()/len(y_true)

accuracy_score(y_test, y_pred)

0.9333333333333333